---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp
  labels:
    name: myapp
    environment: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-webapi
  namespace: myapp
  labels:
    app: myapp-webapi
    component: backend
    environment: production
    version: "2.0"
spec:
  replicas: 3
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: myapp-webapi
  template:
    metadata:
      labels:
        app: myapp-webapi
        component: backend
        environment: production
        version: "2.0"
    spec:
      containers:
        - name: webapi
          image: <docker-hub-account>/myapp-webapi:2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /products
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /products
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-webapi
  namespace: myapp
  labels:
    app: myapp-webapi
    component: backend
    environment: production
spec:
  type: ClusterIP
  selector:
    app: myapp-webapi
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP

