apiVersion: v1
kind: Service
metadata:
  name: myapp-webapp-service
  namespace: webinar4
  labels:
    app: myapp-webapp
spec:
  type: NodePort
  selector:
    app: myapp-webapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30090



